### PR TITLE
v0.0.6

### PR DESCRIPTION
**Pull request by KingGorrin**
This PR adds support for the following:

- Added support for Ledger wallets
- Added [Zenon Ledger Wallet](https://github.com/hypercore-one/znn_ledger_dart) library
- Updated Zenon SDK to v0.0.6 with wallet abstraction support
- Updated library builder workflow to include [Ledger FFI](https://github.com/hypercore-one/ledger_ffi_rs) binaries

**Limitations**

- The following commands are not supported on Ledger wallets: `wallet.createNew`, `wallet.createFromMnemonic`,  `wallet.dumpMnemonic`, `wallet.export`.

**Tests**

- Manual test runs can be found at https://github.com/hypercore-one/znn_cli_dart/tree/feature/ledger/test-runs

**Known issues**

- A Ledger connection becomes invalid when another process opens a new connection to the Ledger. The invalid connection still responds to Ledger commands. The `LedgerTransport` throws a `ResponseError` when it detects invalid responses, but sometimes the response is valid but contains old data from memory. This can cause a Ledger command to return but with old data. The Ledger device is never actually called and in case of a `signTx` command no confirmation is asked. This issue will eventually cause an exception (for example when signing a transaction) and can only happen when creating multiple connections to the ledger.

**Notes**

- All hypercore-one references will be updated and moved to zenon-network once reviewed and approved.

### CODE REVIEW

**Comment by sol-znn** [comment]
I've read through the code for:
- znn_cli_dart v0.0.6
- znn_ledger_dart
- ledger_ffi_rs

Each repo looks clean and ready for testing. Thank you for all the effort you put into this. 
Unfortunately, my scope of testing will be limited since I don't have a Ledger device.
If another maintainer can confirm the code is working as expected, I'll add my approval.

**Comment by KingGorrin** [comment]
Some issues have been fixed while doing a manual test run on Linux using the keyStore wallet.

The results can be found at https://github.com/hypercore-one/znn_cli_dart-manual-tests/pull/1

**Comment by KingGorrin** [comment]
All issues found during the [manual test runs v0.0.6-rc.1](https://github.com/hypercore-one/znn_cli_dart-manual-tests/pull/1) have been fixed in [v0.0.6-rc.2](https://github.com/hypercore-one/znn_cli_dart/releases/tag/v0.0.6-rc.2)

A new manual test run will be made to validate the result.

**Comment by KingGorrin** [comment]
All issues found during the [manual test runs v0.0.6-rc.2](https://github.com/hypercore-one/znn_cli_dart-manual-tests/pull/2) have been fixed in [v0.0.6-rc.3](https://github.com/hypercore-one/znn_cli_dart/releases/tag/v0.0.6-rc.3)

A new manual test run will be made to validate the result.

**Comment by KingGorrin** [comment]
No new issues found during the [manual test runs v0.0.6-rc.3](https://github.com/hypercore-one/znn_cli_dart-manual-tests/pull/3) 

Asking for final review for release...

**Comment by KingGorrin** [comment]
Added docs for ledger and devnet.
Added tests and test runs from znn_cli_dart-manual-tests.
Updated sdk and ledger references.
Fixed token max supply limit.

**Review by vilkris4 — APPROVED** [review]
This looks good to me. I don't have a Ledger device, so I was unable to test the Ledger wallet functionality, but the Ledger related implementations look fine.

**Comment by 0x3639** [comment]
I've ordered a ledger and hope to test this week.

**Review by 0x3639 — APPROVED** [review]

**Pull request merged**
